FROM ubuntu:16.04
MAINTAINER Vinodh Kumar <vinodh.kumar.manickavasagam@verizon.com>

#ENV http_proxy http://10.10.10.10:8080

RUN apt-get -y update && apt-get -y install tree && apt-get -y install vim
